app.controller('inputFilterCtrl',function($scope){
  $scope.names=[
    'Jani',
     'Carl',
     'Margareth',
     'Hege',
     'Joe',
     'Gustav',
     'Birgit',
     'Mary',
     'Kai'
    ];
});
